packages:
  device: !include device.yaml # include our test device setup

external_components:
  - source:
      type: local
      path: components

# Enable logging
logger:
  level: VERBOSE

sensor:
  - platform: vl53l1x_sensor
    name: Default sensor
  - platform: vl53l1x_sensor
    name: Basic settings
    timing_budget: 20ms
    distance_mode: LONG
  - platform: vl53l1x_sensor
    name: Full config
    enable_pin: GPIO10
    distance_mode: MEDIUM
    timing_budget: 200ms
    signal_threshold: 512
    update_interval: 1s
    address: 0x32
    accuracy_decimals: 2
    ambient_rate_sensor:
      name: "ambient_rate"
    avg_signal_rate_sensor:
      name: "avg_signal_rate"
    peak_signal_rate_sensor:
      name: "peak_signal_rate"
    range_status_sensor:
      name: "range_status"
    roi_center: 199
    roi_size:
      x: 4
      y: 4
  - platform: vl53l1x_sensor
    name: ROI settings
    roi_center:
      x: 14
      y: 8
    roi_size:
      x: 6
      y: 6
i2c:
  sda: 4
  scl: 5
